/*
 * Copyright (c) 2023, Callum Rossiter
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.skulltimer.enums.equipment;

import lombok.Getter;
import net.runelite.api.ItemID;

@Getter
public enum Weapons
{
	/*MELEE*/
	//TWO-HANDED SWORDS
	_3RD_AGE_LONGSWORD(ItemID._3RD_AGE_LONGSWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ADAMANT_2H_SWORD(ItemID.ADAMANT_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ANCIENT_GODSWORD(ItemID.ANCIENT_GODSWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ARMADYL_GODSWORD(ItemID.ARMADYL_GODSWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ARMADYL_GODSWORD_OR(ItemID.ARMADYL_GODSWORD_OR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ARMADYL_GODSWORD_DEADMAN(ItemID.ARMADYL_GODSWORD_DEADMAN, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BANDOS_GODSWORD(ItemID.BANDOS_GODSWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BANDOS_GODSWORD_OR(ItemID.BANDOS_GODSWORD_OR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BLACK_2H_SWORD(ItemID.BLACK_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BRONZE_2H_SWORD(ItemID.BRONZE_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	COLOSSAL_BLADE(ItemID.COLOSSAL_BLADE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CORRUPTED_ARMADYL_GODSWORD(ItemID.CORRUPTED_ARMADYL_GODSWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_2H_SWORD(ItemID.DRAGON_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_2H_SWORD_CR(ItemID.DRAGON_2H_SWORD_CR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GIANT_BRONZE_DAGGER(ItemID.GIANT_BRONZE_DAGGER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GILDED_2H_SWORD(ItemID.GILDED_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	IRON_2H_SWORD(ItemID.IRON_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MITHRIL_2H_SWORD(ItemID.MITHRIL_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RUNE_2H_SWORD(ItemID.RUNE_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SARADOMIN_GODSWORD(ItemID.SARADOMIN_GODSWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SARADOMIN_GODSWORD_OR(ItemID.SARADOMIN_GODSWORD_OR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SARADOMIN_SWORD(ItemID.SARADOMIN_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SARADOMIN_BLESSED_SWORD(ItemID.SARADOMINS_BLESSED_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SHADOW_SWORD(ItemID.SHADOW_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SPATULA(ItemID.SPATULA, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	STEEL_2H_SWORD(ItemID.STEEL_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	THE_DOGSWORD(ItemID.THE_DOGSWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	WHITE_2H_SWORD(ItemID.WHITE_2H_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ZAMORAK_GODSWORD(ItemID.ZAMORAK_GODSWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ZAMORAK_GODSWORD_OR(ItemID.ZAMORAK_GODSWORD_OR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),

	//AXES AND BATTLEAXES
	_3RD_AGE_AXE(ItemID._3RD_AGE_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	_3RD_AGE_FELLING_AXE(ItemID._3RD_AGE_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ADAMANT_AXE(ItemID.ADAMANT_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ADAMANT_FELLING_AXE(ItemID.ADAMANT_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ADAMANT_BATTLEAXE(ItemID.ADAMANT_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BLACK_AXE(ItemID.BLACK_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BLACK_BATTLE_AXE(ItemID.BLACK_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BLACK_FELLING_AXE(ItemID.BLACK_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BLESSED_AXE(ItemID.BLESSED_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BRONZE_AXE(ItemID.BRONZE_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BRONZE_BATTLEAXE(ItemID.BRONZE_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BRONZE_FELLING_AXE(ItemID.BRONZE_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CRYSTAL_AXE(ItemID.CRYSTAL_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CRYSTAL_FELLING_AXE(ItemID.CRYSTAL_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DHAROKS_GREAT_AXE(ItemID.DHAROKS_GREATAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_AXE(ItemID.DRAGON_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_AXE_OR(ItemID.DRAGON_AXE_OR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_BATTLEAXE(ItemID.DRAGON_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_BATTLEAXE_CR(ItemID.DRAGON_BATTLEAXE_CR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_FELLING_AXE(ItemID.DRAGON_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ECHO_AXE(ItemID.ECHO_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GILDED_AXE(ItemID.GILDED_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	INFERNAL_AXE(ItemID.INFERNAL_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	INFERNAL_AXE_OR(ItemID.INFERNAL_AXE_OR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	IRON_AXE(ItemID.IRON_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	IRON_BATTLEAXE(ItemID.IRON_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	IRON_FELLING_AXE(ItemID.IRON_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	LEAFBLADED_BATTLEAXE(ItemID.LEAFBLADED_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MITHRIL_AXE(ItemID.MITHRIL_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MITHRIL_FELLING_AXE(ItemID.MITHRIL_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MITHRIL_BATTLEAXE(ItemID.MITHRIL_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RUNE_AXE(ItemID.RUNE_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RUNE_BATTLE_AXE(ItemID.RUNE_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RUNE_FELLING_AXE(ItemID.RUNE_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SOULREAPER_AXE(ItemID.SOULREAPER_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	STEEL_AXE(ItemID.STEEL_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	STEEL_FELLING_AXE(ItemID.STEEL_FELLING_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	STEEL_BATTLEAXE(ItemID.STEEL_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	WHITE_BATTLEAXE(ItemID.WHITE_BATTLEAXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ZOMBIE_AXE(ItemID.ZOMBIE_AXE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),

	//BANNERS
	//todo - banners
	BRONZE_FIST_FLAG(ItemID.BRONZE_FIST_FLAG, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CLAN_VEXILLUM(ItemID.CLAN_VEXILLUM, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CUTTHROAT_FLAG(ItemID.CUTTHROAT_FLAG, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GILDED_SMILE_FLAG(ItemID.GILDED_SMILE_FLAG, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GREEN_BANNER(ItemID.GREEN_BANNER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	LUCKY_SHOT_FLAG(ItemID.LUCKY_SHOT_FLAG, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	PHASMATYS_FLAG(ItemID.PHASMATYS_FLAG, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	PROTEST_BANNER(ItemID.PROTEST_BANNER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RAGING_ECHOS_BANNER(ItemID.RAGING_ECHOES_BANNER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SARADOMIN_BANNER(ItemID.SARADOMIN_BANNER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SHATTERED_BANNER(ItemID.SHATTERED_BANNER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_BANNER(ItemID.TRAILBLAZER_BANNER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_RELOADED_BANNER(ItemID.TRAILBLAZER_RELOADED_BANNER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TREASURE_FLAG(ItemID.TREASURE_FLAG, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TWISTED_BANNER(ItemID.TWISTED_BANNER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ZAMORAK_BANNER(ItemID.ZAMORAK_BANNER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),

	//BLUNT
	_10TH_BIRTHDAY_BANNER(ItemID._10TH_BIRTHDAY_BALLOONS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	_24_CARAT_SWORD(ItemID._24CARAT_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ADAMANT_STAFF_OF_COLLECTION(ItemID.ADAMANT_STAFF_OF_COLLECTION, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ADAMANT_WARHAMMER(ItemID.ADAMANT_WARHAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ASSORTED_FLOWERS(ItemID.ASSORTED_FLOWERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BARRONITE_MACE(ItemID.BARRONITE_MACE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BIRTHDAY_BALLOONS(ItemID.BIRTHDAY_BALLOONS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BIRTHDAY_CAKE(ItemID.BIRTHDAY_CAKE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BLACK_FLOWERS(ItemID.BLACK_FLOWERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BLACK_STAFF_OF_COLLECTION(ItemID.BLACK_STAFF_OF_COLLECTION, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BLACK_WARHAMMER(ItemID.BLACK_WARHAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BLUE_FLOWERS(ItemID.BLUE_FLOWERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BONE_CLUB(ItemID.BONE_CLUB, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BRONZE_STAFF_OF_COLLECTION(ItemID.BRONZE_STAFF_OF_COLLECTION, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	BRONZE_WARHAMMER(ItemID.BRONZE_WARHAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CANDY_CANE(ItemID.CANDY_CANE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CARROT_SWORD(ItemID.CARROT_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CLUELESS_SCROLL(ItemID.CLUELESS_SCROLL, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CRIER_BELL(ItemID.CRIER_BELL, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CURSED_BANANA(ItemID.CURSED_BANANA, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	CURSED_GOBLIN_HAMMER(ItemID.CURSED_GOBLIN_HAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_CANDLE_DAGGER(ItemID.DRAGON_CANDLE_DAGGER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_STAFF_OF_COLLECTION(ItemID.DRAGON_STAFF_OF_COLLECTION, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_WARHAMMER(ItemID.DRAGON_WARHAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_WARHAMMER_CR(ItemID.DRAGON_WARHAMMER_CR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAGON_WARHAMMER_OR(ItemID.DRAGON_WARHAMMER_OR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	DRAMEN_STAFF(ItemID.DRAMEN_STAFF, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	EASTER_BASKET(ItemID.EASTER_BASKET, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	EEK(ItemID.EEK, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ELDER_MAUL(ItemID.ELDER_MAUL, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ELDER_MAUL_OR(ItemID.ELDER_MAUL_OR, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	FINE_MESH_NET(ItemID.FINE_MESH_NET, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	FRYING_PAN(ItemID.FRYING_PAN, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GADDERHAMMER(ItemID.GADDERHAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GIANT_BOULDER(ItemID.GIANT_BOULDER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GIANT_EASTER_EGG(ItemID.GIANT_EASTER_EGG, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GIANT_PRESENT(ItemID.GIANT_PRESENT, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GILDED_SPADE(ItemID.GILDED_SPADE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GILDED_STAFF_OF_COLLECTION(ItemID.GILDED_STAFF_OF_COLLECTION, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GOLDEN_TENCH(ItemID.GOLDEN_TENCH, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GRANITE_HAMMER(ItemID.GRANITE_HAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GRANITE_MAUL(ItemID.GRANITE_MAUL, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GRANITE_MAUL_ONE(ItemID.GRANITE_MAUL_24227, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GRANITE_MAUL_TWO(ItemID.GRANITE_MAUL_12848, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GRANITE_MAUL_THREE(ItemID.GRANITE_MAUL_24225, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	GRANITE_MAUL_FOUR(ItemID.GRANITE_MAUL_20557, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	HALLOWED_HAMMER(ItemID.HALLOWED_HAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	HAM_JOINT(ItemID.HAM_JOINT, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	HAND_FAN(ItemID.HAND_FAN, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	HAUNTED_WINE_BOTTLE(ItemID.HAUNTED_WINE_BOTTLE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	HEAVY_CASKET(ItemID.HEAVY_CASKET, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	HILL_GIANT_CLUB(ItemID.HILL_GIANT_CLUB, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	HUNTING_KNIFE(ItemID.HUNTING_KNIFE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	IMCANDO_HAMMER(ItemID.IMCANDO_HAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	IRON_STAFF_OF_COLLECTION(ItemID.IRON_STAFF_OF_COLLECTION, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	IRON_WARHAMMER(ItemID.IRON_WARHAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	LARGE_SPADE(ItemID.LARGE_SPADE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	LOVE_CROSSBOW(ItemID.LOVE_CROSSBOW, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MAPLE_BLACKJACK(ItemID.MAPLE_BLACKJACK, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MAPLE_BLACKJACK_D(ItemID.MAPLE_BLACKJACKD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MAPLE_BLACKJACK_O(ItemID.MAPLE_BLACKJACKO, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MEAT_TENDERISER(ItemID.MEAT_TENDERISER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MITHRIL_STAFF_OF_COLLECTION(ItemID.MITHRIL_STAFF_OF_COLLECTION, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MIXED_FLOWERS(ItemID.MIXED_FLOWERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MOUSE_TOY(ItemID.MOUSE_TOY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	MYSTIC_CARDS(ItemID.MYSTIC_CARDS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	NUNCHAKU(ItemID.NUNCHAKU, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	NUTCRACKER_STAFF_SWEET(ItemID.SWEET_NUTCRACKER_STAFF, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	NUTCRACKER_STAFF_FESTIVE(ItemID.FESTIVE_NUTCRACKER_STAFF, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	OAK_BLACKJACK(ItemID.OAK_BLACKJACK, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	OAK_BLACKJACK_D(ItemID.OAK_BLACKJACKD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	OAK_BLACKJACK_O(ItemID.OAK_BLACKJACKO, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ORANGE_FLOWERS(ItemID.ORANGE_FLOWERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	PROP_SWORD(ItemID.PROP_SWORD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	PURPLE_FLOWERS(ItemID.PURPLE_FLOWERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RAGING_ECHOS_ADAMANT_TROPHY(ItemID.RAGING_ECHOES_ADAMANT_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RAGING_ECHOS_DRAGON_TROPHY(ItemID.RAGING_ECHOES_DRAGON_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RAGING_ECHOS_RUNE_TROPHY(ItemID.RAGING_ECHOES_RUNE_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RAT_POLE(ItemID.RAT_POLE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RED_FLOWERS(ItemID.RED_FLOWERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ROLLING_PIN(ItemID.ROLLING_PIN, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RUBBER_CHICKEN(ItemID.RUBBER_CHICKEN, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RUNE_STAFF_OF_COLLECTION(ItemID.RUNE_STAFF_OF_COLLECTION, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	RUNE_WARHAMMER(ItemID.RUNE_WARHAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SEVERED_LEG(ItemID.SEVERED_LEG, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SHATTERED_RELICS_ADAMANT_TROPHY(ItemID.SHATTERED_RELICS_ADAMANT_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SHATTERED_RELICS_BRONZE_TROPHY(ItemID.SHATTERED_RELICS_BRONZE_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SHATTERED_RELICS_DRAGON_TROPHY(ItemID.SHATTERED_RELICS_DRAGON_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SHATTERED_RELICS_IRON_TROPHY(ItemID.SHATTERED_RELICS_IRON_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SHATTERED_RELICS_MITHRIL_TROPHY(ItemID.SHATTERED_RELICS_MITHRIL_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SHATTERED_RELICS_RUNE_TROPHY(ItemID.SHATTERED_RELICS_RUNE_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SHATTERED_RELICS_STEEL_TROPHY(ItemID.SHATTERED_RELICS_STEEL_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	SKELETON_LANTERN(ItemID.SKELETON_LANTERN, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	STALE_BAGUETTE(ItemID.STALE_BAGUETTE, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	STATIUSS_WARHAMMER(ItemID.STATIUSS_WARHAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	STATIUSS_WARHAMMER_BH(ItemID.STATIUSS_WARHAMMER_BH, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	STEEL_STAFF_OF_COLLECTION(ItemID.STEEL_STAFF_OF_COLLECTION, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TORAGS_HAMMERS(ItemID.TORAGS_HAMMERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TORAGS_HAMMERS_100(ItemID.TORAGS_HAMMERS_100, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TORAGS_HAMMERS_75(ItemID.TORAGS_HAMMERS_75, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TORAGS_HAMMERS_50(ItemID.TORAGS_HAMMERS_50, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TORAGS_HAMMERS_25(ItemID.TORAGS_HAMMERS_25, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TORAGS_HAMMERS_0(ItemID.TORAGS_HAMMERS_0, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_ADAMANT_TROPHY(ItemID.TRAILBLAZER_ADAMANT_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_BRONZE_TROPHY(ItemID.TRAILBLAZER_BRONZE_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_DRAGON_TROPHY(ItemID.TRAILBLAZER_DRAGON_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_IRON_TROPHY(ItemID.TRAILBLAZER_IRON_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_MITHRIL_TROPHY(ItemID.TRAILBLAZER_MITHRIL_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_RUNE_TROPHY(ItemID.TRAILBLAZER_RUNE_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_STEEL_TROPHY(ItemID.TRAILBLAZER_STEEL_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_RELOADED_ADAMANT_TROPHY(ItemID.TRAILBLAZER_RELOADED_ADAMANT_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_RELOADED_RUNE_TROPHY(ItemID.TRAILBLAZER_RELOADED_RUNE_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TRAILBLAZER_RELOADED_DRAGON_TROPHY(ItemID.TRAILBLAZER_RELOADED_DRAGON_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TROLLWEISS(ItemID.TROLLWEISS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TWISTED_ADAMANT_TROPHY(ItemID.TWISTED_ADAMANT_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TWISTED_BRONZE_TROPHY(ItemID.TWISTED_BRONZE_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TWISTED_DRAGON_TROPHY(ItemID.TWISTED_DRAGON_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TWISTED_IRON_TROPHY(ItemID.TWISTED_IRON_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TWISTED_MITHRIL_TROPHY(ItemID.TWISTED_MITHRIL_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TWISTED_RUNE_TROPHY(ItemID.TWISTED_RUNE_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TWISTED_STEEL_TROPHY(ItemID.TWISTED_STEEL_TROPHY, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TZHAAR_KET_EM(ItemID.TZHAARKETEM, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TZHAAR_KET_OM(ItemID.TZHAARKETOM, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	TZHAAR_KET_OM_T(ItemID.TZHAARKETOM_T, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	UNDEAD_CHICKEN(ItemID.UNDEAD_CHICKEN, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	WHITE_FLOWERS(ItemID.WHITE_FLOWERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	WHITE_WARHAMMER(ItemID.WHITE_WARHAMMER, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	WILLOW_BLACKJACK(ItemID.WILLOW_BLACKJACK, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	WILLOW_BLACKJACK_D(ItemID.WILLOW_BLACKJACKD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	WILLOW_BLACKJACK_O(ItemID.WILLOW_BLACKJACKO, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	YELLOW_FLOWERS(ItemID.YELLOW_FLOWERS, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ZOMBIE_HEAD_A(ItemID.ZOMBIE_HEAD, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),
	ZOMBIE_HEAD_B(ItemID.ZOMBIE_HEAD_19912, WeaponAnimations.UNDEFINED, WeaponHitDelay.MELEE_STANDARD, WeaponHitDelay.NOT_APPLICABLE),


	/*RANGED*/

	/*MAGIC*/
	;

	private final int weaponID;
	private final WeaponAnimations weaponAnimations;
	private final WeaponHitDelay standardHitDelay;
	private final WeaponHitDelay specialHitDelay;

	Weapons(int weaponID, WeaponAnimations weaponAnimations, WeaponHitDelay standardHitDelay, WeaponHitDelay specialHitDelay)
	{
		this.weaponID = weaponID;
		this.weaponAnimations = weaponAnimations;
		this.standardHitDelay = standardHitDelay;
		this.specialHitDelay = specialHitDelay;
	}
}
